# fly.toml app configuration file generated for bookkss on 2023-07-21T08:13:09-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "bookkss"
primary_region = "sjc"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
